services:
  - type: web
    name: mholly-web-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        value: mholly.development@gmail.com
      - key: ADMIN_EMAIL
        value: mholly.development@gmail.com
      - key: SITE_URL
        sync: false
